# Generated by Django 2.2.5 on 2019-09-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_match', '0002_auto_20190907_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='contact',
            field=models.TextField(default='', max_length=256, verbose_name='Contact'),
            preserve_default=False,
        ),
    ]
