# Generated by Django 2.2.5 on 2019-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_match', '0003_tutor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
