# Generated by Django 2.2.5 on 2019-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_match', '0004_tutor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='template',
            field=models.CharField(blank=True, max_length=256, verbose_name='Template'),
        ),
    ]
